INSERT INTO SIGN_TOGETHER(TOGETHER_SIGN,TOGETHER_NO,MEMBER_ID,TOTAL_ACHV,ACHV,STATUS)
VALUES(1,'100-1','soyoung',6,1,1);
INSERT INTO SIGN_TOGETHER(TOGETHER_SIGN,TOGETHER_NO,MEMBER_ID,TOTAL_ACHV,ACHV,STATUS)
VALUES(2,'200-1','youngyoung',10,4,1);
INSERT INTO SIGN_TOGETHER(TOGETHER_SIGN,TOGETHER_NO,MEMBER_ID,TOTAL_ACHV,ACHV,STATUS)
VALUES(3,'500-1','aran',6,0,0);